Updating docs to have ItemPrototype information
peter-kish/gloot pull request #3
Opened 2022-06-25 18:25 UTC by Polatrite

2022-06-26 13:51 UTC, peter-kish commented
Hey, thanks for the input!
I left some comments, I hope not too nit-picky...

2022-06-26 15:21 UTC, Polatrite commented
Peter, thanks for taking a look, but I didn't see any additional comments on the files. What would you like fixed up? 😃

2022-06-26 15:23 UTC, peter-kish requested changes

2022-06-26 15:24 UTC, peter-kish commented
> Peter, thanks for taking a look, but I didn't see any additional comments on the files. What would you like fixed up? 😃

Forgot to publish the review :)

2022-06-26 15:29 UTC, Polatrite commented on docs/item_prototype.md
> +The following properties will be used by InventoryStacked: `['image', 'name', 'stack_size', 'weight']`
Yeah, good catch! These should be links as well.

2022-06-26 15:33 UTC, Polatrite commented on docs/docs.md
> +* [`ItemPrototype`](./item_prototype.md)
How would you feel about `Item Protoset (JSON)` being in the title, just to further disambiguate between `ItemProtoset` and `Item Protoset` in backlinks from other files?

2022-06-26 15:38 UTC, peter-kish commented on docs/docs.md
> +* [`ItemPrototype`](./item_prototype.md)
Sounds good :)

2022-06-26 16:30 UTC, Polatrite commented
Revisions up, let me know what you think. Would love to hear your plans for the future and where I could help out!

2022-06-27 07:49 UTC, merged

2022-06-27 07:56 UTC, peter-kish commented
Looks good, thanks! For now I'll probably focus on the stability of existing features before adding new ones. Trying to keep the whole interface as simple as possible.
If you're comfortable with Gdscript, I can let you know when something comes up where I need help. If not, the docs will need updates sooner or later :)